/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as IlanVerRouteImport } from './routes/ilan-ver'
import { Route as IlanKurallariRouteImport } from './routes/ilan-kurallari'
import { Route as GuvenliKullanimRouteImport } from './routes/guvenli-kullanim'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as AraRouteImport } from './routes/ara'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SikayetIdRouteImport } from './routes/sikayet.$id'
import { Route as IlanIdRouteImport } from './routes/ilan.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanVerRoute = IlanVerRouteImport.update({
  id: '/ilan-ver',
  path: '/ilan-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanKurallariRoute = IlanKurallariRouteImport.update({
  id: '/ilan-kurallari',
  path: '/ilan-kurallari',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenliKullanimRoute = GuvenliKullanimRouteImport.update({
  id: '/guvenli-kullanim',
  path: '/guvenli-kullanim',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const AraRoute = AraRouteImport.update({
  id: '/ara',
  path: '/ara',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SikayetIdRoute = SikayetIdRouteImport.update({
  id: '/sikayet/$id',
  path: '/sikayet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanIdRoute = IlanIdRouteImport.update({
  id: '/ilan/$id',
  path: '/ilan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ara': typeof AraRoute
  '/giris': typeof GirisRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenli-kullanim': typeof GuvenliKullanimRoute
  '/ilan-kurallari': typeof IlanKurallariRoute
  '/ilan-ver': typeof IlanVerRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ilan/$id': typeof IlanIdRoute
  '/sikayet/$id': typeof SikayetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ara': typeof AraRoute
  '/giris': typeof GirisRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenli-kullanim': typeof GuvenliKullanimRoute
  '/ilan-kurallari': typeof IlanKurallariRoute
  '/ilan-ver': typeof IlanVerRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ilan/$id': typeof IlanIdRoute
  '/sikayet/$id': typeof SikayetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ara': typeof AraRoute
  '/giris': typeof GirisRoute
  '/gizlilik': typeof GizlilikRoute
  '/guvenli-kullanim': typeof GuvenliKullanimRoute
  '/ilan-kurallari': typeof IlanKurallariRoute
  '/ilan-ver': typeof IlanVerRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ilan/$id': typeof IlanIdRoute
  '/sikayet/$id': typeof SikayetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ara'
    | '/giris'
    | '/gizlilik'
    | '/guvenli-kullanim'
    | '/ilan-kurallari'
    | '/ilan-ver'
    | '/nasil-calisir'
    | '/sitemap.xml'
    | '/ilan/$id'
    | '/sikayet/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ara'
    | '/giris'
    | '/gizlilik'
    | '/guvenli-kullanim'
    | '/ilan-kurallari'
    | '/ilan-ver'
    | '/nasil-calisir'
    | '/sitemap.xml'
    | '/ilan/$id'
    | '/sikayet/$id'
  id:
    | '__root__'
    | '/'
    | '/ara'
    | '/giris'
    | '/gizlilik'
    | '/guvenli-kullanim'
    | '/ilan-kurallari'
    | '/ilan-ver'
    | '/nasil-calisir'
    | '/sitemap.xml'
    | '/ilan/$id'
    | '/sikayet/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AraRoute: typeof AraRoute
  GirisRoute: typeof GirisRoute
  GizlilikRoute: typeof GizlilikRoute
  GuvenliKullanimRoute: typeof GuvenliKullanimRoute
  IlanKurallariRoute: typeof IlanKurallariRoute
  IlanVerRoute: typeof IlanVerRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  IlanIdRoute: typeof IlanIdRoute
  SikayetIdRoute: typeof SikayetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan-ver': {
      id: '/ilan-ver'
      path: '/ilan-ver'
      fullPath: '/ilan-ver'
      preLoaderRoute: typeof IlanVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan-kurallari': {
      id: '/ilan-kurallari'
      path: '/ilan-kurallari'
      fullPath: '/ilan-kurallari'
      preLoaderRoute: typeof IlanKurallariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guvenli-kullanim': {
      id: '/guvenli-kullanim'
      path: '/guvenli-kullanim'
      fullPath: '/guvenli-kullanim'
      preLoaderRoute: typeof GuvenliKullanimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ara': {
      id: '/ara'
      path: '/ara'
      fullPath: '/ara'
      preLoaderRoute: typeof AraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sikayet/$id': {
      id: '/sikayet/$id'
      path: '/sikayet/$id'
      fullPath: '/sikayet/$id'
      preLoaderRoute: typeof SikayetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$id': {
      id: '/ilan/$id'
      path: '/ilan/$id'
      fullPath: '/ilan/$id'
      preLoaderRoute: typeof IlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AraRoute: AraRoute,
  GirisRoute: GirisRoute,
  GizlilikRoute: GizlilikRoute,
  GuvenliKullanimRoute: GuvenliKullanimRoute,
  IlanKurallariRoute: IlanKurallariRoute,
  IlanVerRoute: IlanVerRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  IlanIdRoute: IlanIdRoute,
  SikayetIdRoute: SikayetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
